qiskit-community/qiskit-metal

tox.ini
work in progress - triggered docs incomplete. Working on completion
=> doc trigger fix (work in progress)

docs/tut/tutorials/Deep Dive.ipynb, qiskit_metal/__init__.py, setup.py
with this PR/commit we will trigger the first Zenodo DOI and first PyPi (thus needs to be rebased after all the other PRs are merged)
=> Freeze commit for the release: 0.0.2 -> 0.0.3

README.md, tutorials/4 Plugin Developer/Create new QRenderer.ipynb
For user to sign up for live tutorials from the github repo.
=> Tutorial sign-up form + some cleanup on tutorial 4

tutorials/7 Documentation/Accessing qiskit-metal documentation.ipynb
n/a
No
No
Yes
Fixed bug in notebook 7
=> clarified notebook 7

README.md, docs/faq.rst
#435
no
yes
yes
Certain users saw PyQode crashing because they were missing Command Line tools
=> install CLtools for macos in README

.gitignore
`user component` deletion in PR 399
no
no
yes
`user_component` directory for user-created, local components was accidentally renamed in #25 so it's added back here
=> Add user_component dir and update .gitignore 

tutorials/8 Full Design Flow Examples/Full_Chip_Design_01.ipynb
Closes Issue #449.
I ran the notebook.
no
yes 
Make the length of RouteMeander longer to stop the warnings.
=> Stop the warnings.

environment.yml
none
No
No
Yes
Added pytest to environment.yml
=> Added pytest to environment.yml

README.md, environment.yml, requirements-dev.txt
None
No
No
No
moving pytest to requirements-dev
=> moving pytest to requirements-dev

docs/workflow.rst
There was a typo in  https://qiskit.org/documentation/metal/workflow.html
No
yes
yes
All details can be find in Files changes section
Please let me know if any editing needed.
Thank You
=> Fixed a Typo

docs/apidocs/qiskit_metal.analyses.Sweeping.rst, docs/qiskit_metal.analyses.Sweeping.rst, qiskit_metal/analyses/sweep_options/sweeping.py, tutorials/6 Analysis/Sweep_an_option_get_hfss_eigenmode_matrix.ipynb
The method sweep_one_option_get_eigenmode_solution_data had two more arguments. Also, reformat the data to use only 80 columns width. 
I updated the notebook to use the additional arguments and ran that manually.
yes to both in notebook and docstrings.
yes
This should allow user to have better output of data.
When merged, the branch can be deleted and issue #466 would be closed.
=> Issue #466 add arguments to 

qiskit_metal/renderers/renderer_gds/make_cheese.py
When cheesing is on, the ground plane was not subtracted by the cheesing holes.  Also the path shapes was missing. 
no
no
yes
I ran run_all_tests, it passes.
=> Fix the diff conflicting with diff with ground. Fix issue #470

README.md, README_Tutorials.md
Sharing the tutorial schedule in a way that we can update the content. We can pin this page to the slack channel and to the e-mails, so that we can control and update as needed.
=> Tutorial Schedule

README.md, docs/index.rst
Closes #475 
Not necessary
Yes
Yes
Added tutorial video link to the docs, and link in the README.
=> Added tutorial video link to the docs

tutorials/5 All QRenderers/5.1 Ansys/Ansys QRenderer.ipynb
None
No
No
Yes
Fixed bug in ansys qrenderer notebook that caused it to fail.
=> bug fix in ansys qrenderer notebook

qiskit_metal/designs/design_base.py, qiskit_metal/designs/design_planar.py, qiskit_metal/designs/interface_components.py, qiskit_metal/designs/net_info.py, qiskit_metal/qlibrary/core/base.py
Lint just the files in designs directory and base.py.  This does NOT close issue #420.  
I ran run_all_tests. 
no
yes
This addresses linting for just designs directory and base.py.  It does NOT close the issue for lint.  However, after the merge, this branch can be deleted.
=> Lint just the files in designs directory and base.py.

README_Tutorials.md
=> updated tutorial md

docs/workflow.rst
=> Updated roadmap

qiskit_metal/_gui/widgets/create_component_window/parameter_entry_window.py
#598 
no
no
yes
Updated default args that display in Param Entry Window
=> updated args

qiskit_metal/_gui/widgets/create_component_window/model_view/tree_model_param_entry.py
#591 
no
no
no
When adding args to a component, you can now nest in a dictionary by being in any (non-dictionary) element of that dictionary and clicking "Nest"
=> nest dictionary

qiskit_metal/renderers/renderer_gds/make_cheese.py
Issue #615 
No, but I ran the GDS notebook as a sanity check.
no, not applicable
yes
Add an argument for precision to for method named fracture.
=> Add precision to fracture method.

qiskit_metal/renderers/renderer_gds/gds_renderer.py
Closes issue 629.  
I checked the output in vscode.
NA
Use correct information from row of dataframe.
=> The row.key information does not exist, use more meaningful inforation.

docs/tut/index.rst
Closes #656 
No
Yes
Yes
Added link to video tutorials in tutorials page - both at top and bottom of the page.
=> Added link to video tutorials in tutorials page

docs/faq.rst, environment.yml
feedback from the QSciTech participants to guide the installation of the editor-mode (github, not PyPl) qiskit-metal
no
yes
yes
*should test this on a mac and on a windows at least.*
=> Install tips from QSciTech participants

docs/installation.rst, docs/tut/index.rst
None
No
Yes
Yes
The youtube logo's were very large for the page.  I reduced them to 60% of the original size.
=> reduced youtube logo size

qiskit_metal/_gui/widgets/create_component_window/model_view/tree_model_param_entry.py
#581 
no
yes
yes
In Create Component Window, you can now add rows when highlighted inside of a dictionary
=> can now add rows inside dict

qiskit_metal/_gui/widgets/create_component_window/model_view/tree_model_param_entry.py
#592 
no
yes
yes
Fixed dangling phantom nodes left by deleting dictionaries
=> fixed dangling branches

qiskit_metal/_gui/main_window.py, qiskit_metal/_gui/main_window_base.py
#519 
no
yes
yes
Cancel button on closing window now works
=> fixed cancel button

requirements-dev.txt
Fixing docs temporarily by limiting the nbsphinx library version.
TODO: identify what breaks the tut build and remove it (or flag to the nbsphinx package owners)
=> Fix doc build

README_Tutorials.md
Update on the tutorial timeline - summer break extension, and some of the old pieces
=> live tut update

qiskit_metal/analyses/quantization/lumped_oscillator_model.py
bus highlighted by @fgnyilmaz and @quantum-quant
=> hot-fix self.sim type handling

docs/tut/4-Analysis/4.12-Analyze-a-resonator.ipynb, tutorials/4 Analysis/B. Advanced - Direct use of the renderers/4.12 Analyze a resonator.ipynb
=> typo fix 4.12 tutorial

qiskit_metal/analyses/quantization/lumped_oscillator_model.py
=> bug-fix pr 707

qiskit_metal/renderers/renderer_ansys/hfss_renderer.py
plotting results of hfss simulations did not have axis labels or units
no
no
yes
the function plot_params in hfss_renderer now includes axis labels
=> updated plot_params

tutorials/3 Renderers/3.4 How do I make my custom QRenderer.ipynb, tutorials/resources/skeleton_renderer.py
NA
Yes
yes
yes
Updated the skeleton renderer
Added the code required to make skeleton renderer work again. This code includes three methods.
=> Skeleton renderer

README_Tutorials.md
Just  double check the dates and possible agenda items.
=> Update the tutorial schedule.

qiskit_metal/designs/net_info.py, qiskit_metal/qgeometries/qgeometries_handler.py
n/a
no
no
yes
This pull request fixing warnings caused by creating an environment in pandas 1.4.
=> Fixed warnings for pandas 1.4

environment.yml, requirements.txt
This will address part of issue #766.  However will still need to add testing for python 3.10 in a separate pull request.
=> Remove the version of numpy since qutip has updated the lib.

docs/workflow.rst
Yes
Yes
This fixes some typos in the _Roadmap_ section in docs
=> Fix typos in Roadmap section in docs

README_Tutorials.md
Close issue #777 when this merges.
no
yes
yes
The YouTube links have been generated by communications group from webx.  
This just adds the links to the md doc.
=> Add the YouTube hyperlinks to tutorials agenda.

README_Tutorials.md
Update the information in the tutorial documents.
=> Add link to new YouTube video and update agenda for next week.

qiskit_metal/draw/utility.py, qiskit_metal/renderers/renderer_mpl/mpl_renderer.py
This merge closes issue #782.  
no
no
yes
This fixes the bug in issue #782 , so now fillet works as it used to.
=> 782 fillet gui

README_Tutorials.md
=> Add youtube video to tutorial history.

qiskit_metal/analyses/quantization/lom_core_analysis.py
* Implemented double-side loaded TL resonator model
* New TL model nicely resolves to single-side loaded and/or single-side shorted models under approriate boundary conditions
* Generalize multi-node subsystems which were necessary for the double-sided TL
model
* Checked and verified that the double-side loaded TL model can recover single-side loaded results under approriate bouonary conditions
* Check that new changes do not break existing tutorials/applications
yes
yes
=> Double-side loaded transmission line model and multi-node subsystems

qiskit_metal/analyses/hamiltonian/states_energies.py, qiskit_metal/analyses/quantization/lom_core_analysis.py
Significanty improve performance of LOM by more than 3x:
* allow using pre-computed s_remove and s_keep matrices
* caching c_k, c_inv_k, l_inv_k
* recorgnize code to remove duplicate computation, e.g., calling hamiltonian() twice...
* disable check_validity on add_interaction()
* vecotorize extract_energies() so all expensive computations happen as numy matrices manipulations and operations on said matrices which is much faster than nested functions and searches in loops.
yes
yes
=> Optimize-performance

environment.yml, qiskit_metal/__init__.py, requirements.txt, setup.py
Version bump for pyEPR sign fix
No
No
Yes
Bump qiskit metal to 0.1.2
Bump pyEPR to 0.8.5.7
The pyEPR sign bug fix in the last release was itself bugged. We went back and fixed this properly. It required running .evaluate() on the real part of the voltage.
=> Bump version of qiskit metal to 0.1.2 and pyepr to 0.8.5.7

docs/conf.py
=> Fix typo for docs for issue #823

environment.yml
Can add pyaedt to build for future.
=> Add pyaedt for future use.

README_Tutorials.md
Add the new tutorial to the list in repo
When merged, this will close #838
=> 838 add talk documenation

README_Tutorials.md
=> Add tutorial by Connor Bowman to youtube channel.

qiskit_metal/renderers/renderer_gmsh/gmsh_renderer.py
Closes #846 
Closes #842 
No
Yes
Yes
This PR is a work in progress and solves the issue which occurs when giving thickness=0 for a layer in MultiPlanar with Gmsh renderer.
Functions to be changed (potentially):
=> Fix for `thickness=0` and 3D junctions issue with Gmsh renderer

docs/circuit-examples/index.rst
-
Not applicable
Yes
Yes
Fixes section title typo from `Input-Ouput Coupling` to `Input-Output Coupling`
-
=> Fix docs typo in section title

README_developers.md, hooks/pre-commit
Issue #874 
Verified all changes myself.
Yes
Yes
I updated the pre-commit hook to only run on .py files, not .ipynb files. I also updated the qiskit-metal\README_developers.md.
Branch can be deleted after PR is merged.
=> 874 pre commit hook

.github/workflows/main.yml
This PR version locks tox to address a breaking change. It also updates the versions of our GitHub Actions.
N/A
N/A
N/A
N/A
N/A
=> Version lock tox and update actions

.github/workflows/docs.yml, .github/workflows/main.yml, .github/workflows/release.yml
=> Change Key and name to better document CI.

.github/workflows/docs.yml
=> Limit deployed version for ubuntu.

.github/workflows/docs.yml, tox.ini
=> Use python 3.9

README.md, README_Tutorials.md, docs/index.rst
Related to https://github.com/Qiskit/qiskit.org/issues/2959
=> Update slack invite link
