setup.py

This commit fixes serval issues with the package metadata. The first is
the trove classifiers were incorrectly listing the package as supporting
multiple versions of python, however the current metal repo only
supports 3.7 (and a narrow subset too) so the unsupported python
versions are removed. Additionally, it was listing metal as a console
application which it is not, it's a GUI and an API. Then additional
metadata is added to add links to the tracker, documentation, and source
repo.

Fix package metadata

---

docs/_templates/theme_variables.jinja

Override jinja variables to point navbar directly to Metal Github page

---

qiskit_metal/qlibrary/connectors/cpw_hanger_t.py
qiskit_metal/tests/test_components_2_options.py

The enhancement issue #445 (also from me)
yes (modified the test_components_2_options file)
no (I did not find the location where the new option would be included)
yes
This is a minimal change to improve the customizability of cpw_hanger_t elements on chips and set them to a specific value instead of two times the coupling length. This should give people more freedom in their chip design.

Included the length of the hanging cpw of the cpw_hanger_t as an option

---

qiskit_metal/renderers/renderer_ansys/hfss_renderer.py
qiskit_metal/renderers/renderer_ansys/q3d_renderer.py

…  Fix for eigenmode and drivenmodal also.
When using pinfo.setup property variables.  The format for frequency is different than other property variables.
This fix addresses the difference for frequency for q3d, eigenmode and driven modal.
Ran run all tests.
no, the doc strings were accurate.
yes
Tested the code manually for all three design types.
When merged, closes Issue #464.

edit setup(), passing freq to Ansys

---

tutorials/Appendix/Quick Topic Tutorials Notebooks/Transmon_Analytics_HCPB_Demo.ipynb

Added a demo notebook to re-create the transmon eigenvalue plots as a function of offset charge originally found in J. Koch et al. PRA 76, 042319 (2007)
This PR addresses issue #218 
Yes, this PR is for a demo notebook which itself is a test that the required plots are generated correctly. 
No, but the demo notebook is well-documented and self-contained. 
This PR is for a demo notebook which creates transmon analytics plots of eigenvalues as a function of offset charge. The figures match those found in the J. Koch PRA (2007) paper. This PR closes issue #218, and this branch can be deleted upon successful merge. 
Please see above.

Added Transmon_Analytics_HCPB_Demo

---

docs/build_docs.py

Closes #134 
Not needed
Not needed
Yes
Fixed the bug that prevented metal from starting in the event that the docs build was interrupted by simply catching the keyboard interrupted and terminating gracefully.

fixed bug preventing metal from starting if docs build interrupted

---

qiskit_metal/_gui/widgets/edit_component/component_widget.py

#603 
no
no
no
Background is now consistent:

Component Widget's textSource bg colour is now that of pygment's highlight

---

qiskit_metal/_gui/widgets/create_component_window/parameter_entry_window.py
qiskit_metal/_gui/widgets/edit_component/component_widget.py

#595 
no
no
no
Param Entry Window's Source tab not has a white background instead of white highlights on a black background.

matching background color of widget to highlight color of pygments

---

qiskit_metal/qlibrary/qubits/Transmon_Interdigitated.py
qiskit_metal/qlibrary/qubits/transmon_concentric.py
qiskit_metal/tests/test_qlibrary_2_options.py

Add JJs to qgeometry as junctions rather than polys.
This PR addresses issue #639. This branch can be deleted upon successful merge. 
There is already a tutorial notebook to test that the interdigitated transmon is drawn correctly. I've tested that this notebook still works as expected. I've also run a manual test to check that the concentric transmon is drawn correctly. 
I've updated comments in the qcomponent files, but otherwise the documentation already exists for these qcomponents. 
Yes.
Modified two qcomponents (interdigitated transmon and concentric transmon) so that the josephson junctions are rendered as "junctions" rather than "poly". 
Draw JJs as linestrings rather than shapely objects and add them to the qgeometry as "junctions" rather than "poly"s. In this way, they appear …

Updates to interdigitated and concentric transmon qcomponents

---

qiskit_metal/analyses/simulation/lumped_elements.py
qiskit_metal/analyses/simulation/scattering_impedance.py

No corresponding issue - this is a followup bug fix for PR 641, which is already closed.
No
None needed - no change in docstrings
Yes
PR 641 added vars_to_initialize (which contains variable info for sweeping purposes) in its _render() method, which affects its subclasses EigenmodeSim, LumpedElementsSim, and ScatteringImpedanceSim. Only EigenmodeSim was modified in that PR. This PR adds vars_to_initialize to the latter 2 classes.
See above.

Add variables to LOM and scattering Qsimulators

---

qiskit_metal/analyses/core/simulation.py
qiskit_metal/analyses/quantization/lumped_oscillator_model.py
qiskit_metal/analyses/simulation/lumped_elements.py
tutorials/4 Analysis/A. Core - EM and quantization/4.01 Capacitance and LOM.ipynb

It was brought up in the #metal slack channel from @bicycle315 that her use-case requires to run simulations remotely, due to license constraints. With this PR we de-embed the "data harvesting" method (`_get_results_from_renderer()`) from the "analysis run" method (`_analyze(self)`), so that the former can be called independently from the latter, thus enabling her to run the simulations from the Ansys GUI and later harvest the results.
@bicycle315 also brought to our attention that when the sim.capacitance_matrix is empty, there is an non-handled error if we try to run the analysis methods. I thus modified the code to make sure the error is handled by showing a descriptive message
these methods are not currently covered by unit test
yes
yes

Get information after simulations from renderer gui

---

qiskit_metal/renderers/renderer_gds/gds_renderer.py
qiskit_metal/renderers/renderer_gds/make_cheese.py

Junction being added to GDS twice for positive mask with cheesing.  
no
The source code explains choice of arguments.
yes
In the top_main_# for positive mask has the cell for junction in it as a reference. 
The cell top_main_# has paths and polys.  The other cells should not be part of the boolean subtraction.  For example the junction. 
When getting the polygons, don't use the cells for junction.

Junction being added to GDS twice for positive mask with cheesing.

---

qiskit_metal/renderers/renderer_mpl/mpl_toolbox.py

Issue #735 : https://github.com/Qiskit/qiskit-metal/issues/735
no (No function changes)
yes
yes
Changed the way axis is cleared while rendering the design
Using axis.clear() instead of the previous method of clearing every subelement at a time. This might be a temporary fix, but the tests pass. I do not know what issues this might cause or why it was done the way it was done before.

Fix for Issue #735

---

qiskit_metal/analyses/quantization/lom_core_analysis.py

Fixed bug when cap matrices have different sizes. 
Need to flatten list of nodes before applying numpy.unique() 
yes
yes

fixed bug when cap matrices have different sizes

---

qiskit_metal/qlibrary/core/base.py

add_pin() and add_qgeometry() were exclusively using the default values layer=1 and chip='main', since they have not been passed in by most QComponents' make() functions.
no
yes
yes
Changed the default values to None, which then pull values from self.options.

771 chipname and layer sub

---

qiskit_metal/analyses/quantization/lom_core_analysis.py

This fixes a newly discovered bug which happens when there's no node to remove in the caculation of reduced capacitance and inductance matrix. In this case, S_k should just be the identity matrix. 
yes

fix bug when there's no node to remove

---

qiskit_metal/__init__.py
setup.py

Create a new pip tag version 0.1.0.
No
No
Will be in pip release notes.

Create a new tag for pip release.

---

qiskit_metal/draw/utility.py
qiskit_metal/tests/test_draw.py

#808 
Yes. Modified `qiskit_metal/tests/test_draw.py` to include tests for new code.
Yes
Yes
Added a 3D vector class `Vec3D` for extending functionality to be used by future renderers (like Gmsh).
Gmsh renderer uses 3D vectors natively to avoid the conversion and confusion between 2D and 3D vectors. this class adds the feature to use 3D vectors and extends the functionality.

Added 3D vector class

---

qiskit_metal/qlibrary/qubits/transmon_pocket_cl.py

The name of the component- Transmon Pocket Connector Lines has been replaced with - Transmon Pocket Charge Line
#809 
Tested by re-running Metal GUI
Yes
Yes
The name of the component- Transmon Pocket Connector Lines has been replaced with - Transmon Pocket Charge Line
N/A

Updated the component name for GUI

---

environment.yml
qiskit_metal/__init__.py
requirements.txt
setup.py

N/A
No
No
Yes
This PR bumps the version numbers for qiskit metal and pyEPR to pull in a pyEPR fix to a bug that was causing EPR to always be positive.
Qiskit-metal version bumped from 0.1.0 to 0.1.1
pyEPR version bumped from 0.8.5.5 to 0.8.5.6

Bump version of qiskit-metal pyEPR version for EPR sign fix

---

.github/workflows/docs.yml
.github/workflows/main.yml
requirements-dev.txt
tox.ini

Since sphinx was updated yesterday, update the python version..

---

qiskit_metal/designs/__init__.py
qiskit_metal/designs/design_multiplanar.py
qiskit_metal/toolbox_metal/layer_stack_handler.py
tutorials/resources/layer_stack_data_example.csv

closes issue #824.  
no
Add the concept of MultiPlanar class. Have the layer_stack_handler register to the class.
I used the below code to test this. 
```
import qiskit_metal as metal
from qiskit_metal import designs, draw
from qiskit_metal import MetalGUI, Dict, open_docs
from qiskit_metal.toolbox_metal.layer_stack_handler import LayerStackHandler
design = designs.MultiPlanar()
lsh = LayerStackHandler(design)
print(lsh.ls_df)
material, fill, z_coord, thickness, chip_name = lsh.get_properties_for_layer_datatype(
['material', 'fill', 'z_coord', 'thickness', 'chip_name'], 1)
print(f'{material},{fill},{z_coord},{thickness}, {chip_name}')
material, fill, z_coord, chip_name, thickness = lsh.get_properties_for_layer_datatype(
['material', 'fill', 'z_coord', 'chip_name', 'thickness'], 4, 0) …
```

824 multi planar

---

qiskit_metal/designs/design_multiplanar.py

#828 
No
No
Yes
Fixes the issue with getting tuple instead of string for `sample_holder_top` in `self._uwave_package`

Fixed issue with self._uwave_package

---

requirements.txt

Add pyaedt as a dependency to troubleshoot CI error

Add pyaedt as a dependency

---

qiskit_metal/renderers/renderer_base/renderer_base.py
qiskit_metal/toolbox_metal/__init__.py
qiskit_metal/toolbox_metal/bounds_for_path_and_poly_tables.py
qiskit_metal/toolbox_metal/layer_stack_handler.py

Closes issue #832 
This is for Multiplanar Design with use of the layer_stack_handler.

832 box plus buffer vs chips for Multiplanar design.

---

README_developers.md

No issue made for this. 
Add directions and command to help user to determine the cause of linting CI failure.

Add information for developers to deal with CI linting failures.

---

qiskit_metal/toolbox_metal/layer_stack_handler.py

Usage for future renderers for pyaedt and multilayer.

Provide data in format for usage when fill==True.

---

environment.yml
qiskit_metal/renderers/renderer_gmsh/gmsh_renderer.py
qiskit_metal/toolbox_metal/bounds_for_path_and_poly_tables.py
requirements.txt

…s that are rendered.
When merged, issue #852  can be closed.
no
Yes, in docstrings.
yes

Add a dataframe to return Tuple, so that user can get a list of all valid geometries from path, poly, and junction.

---

qiskit_metal/renderers/renderer_gmsh/gmsh_renderer.py

Closes #857 
Did external testing
No
Yes
Added some code to fix the exported `.geo_unrolled` file from Gmsh renderer to not have mesh size fields and also set the factory method to "OpenCASCADE" in the file manually.
N/A

Fix for including mesh size fields in `.geo_unrolled` file and SetFactory()

---

qiskit_metal/tests/test_toolbox_metal.py

[#856 Add Additional Test Cases](https://github.com/Qiskit/qiskit-metal/issues/856)
yes
no (added comments in test_toolbox_metal.py)
yes
Added unit tests for the following functions/methods:
- input_error
- open_docs
- orient_me
- get_platform_info
- extract_value_unit
- aligned_pts
Added unit tests to validate these functions/methods. Completed a portion of issue #856 . I would like to save this branch to continue developing on it.

856 toolbox metal test cases

---

qiskit_metal/designs/design_base.py
qiskit_metal/designs/design_multiplanar.py
qiskit_metal/renderers/renderer_gds/gds_renderer.py

Close issue #865 when merged.  
No
Yes, within the GDS renderer module.
yes
Test rendering a design made with multiplanar design.
Can delete branch after merging.

865 gds handle multiplanar design with multiple chip names and layer. 

---

.github/workflows/docs.yml
.github/workflows/main.yml
requirements-dev.txt
tox.ini

855 pyside2

---

tox.ini

Use Skip install=true and EXPLICITLY identify the dependencies.

Improve syntax.

---

.github/workflows/docs.yml
.github/workflows/main.yml
.github/workflows/release.yml

N/A
N/A
N/A
Yes
This replaces the qt5-default package with qtbase5-dev and  qt5-qmake for installation on Ubuntu 22.04.
N/A

Replace qt5-default dependency for Ubuntu 22.04

---

qiskit_metal/analyses/sweep_and_optimize/sweeper.py

Fixes #907
No. I'm not sure how to add test cases for this particular case.
No.
Yes.
Currently, when a run fails during the execution of Sweeper class' run_sweep method, the warning message, does not tell which option name or option value that failed.
It will be useful to add which option name + option value (key) combination thatdidn't execute properly for reference in case the user wantst to run the sweeperagain for the failed option values
This commit adds the option name and option value that failed to the warning message.

Display option name and option value of failed runs in the Sweeper class' `run_sweep` method

---

qiskit_metal/analyses/sweep_and_optimize/sweeper.py

Reverts Qiskit/qiskit-metal#909

Revert "Display option name and option value of failed runs in the Sweeper class' `run_sweep` method"

---

qiskit_metal/analyses/sweep_and_optimize/sweeper.py

Fixes #907. There was a previous PR on this issue at PR [909](https://github.com/Qiskit/qiskit-metal/pull/909) which was merged to main branch and reverted at PR [912](https://github.com/Qiskit/qiskit-metal/pull/912) because the solution merged was not working. This PR fixes the issue in PR [909](https://github.com/Qiskit/qiskit-metal/pull/909).
No. I'm not sure how to add test cases for this particular case.
No.
Yes.
Currently, when a run fails during the execution of Sweeper class' run_sweep method, the warning message, does not tell which option name or option value that failed.
It will be useful to add which option name + option value (key) combination thatdidn't execute properly for reference in case the user wantst to run the sweeperagain for the failed option values
This commit …

Display option name and option value of failed runs in the Sweeper class' run_sweep method

---

README_Tutorials.md
docs/index.rst

Add links into the tutorials within the documentation.

Add Elmer/Gmsh tutorial

---

environment.yml

#924
Yes, and tested that gui would run
Yes
Yes
I specified the version of pyside2 to be 5.15.8

Updated pyside2 version in environment.yml

---

README_Gmsh_Elmer.md

#933 
Yes, can be checked on #933 and on #metal
Yes.
Yes.
- Added a note for ElmerFEM for Windows.
Installing ElmerFEM-gui-mpi-Windows-AMD64 instead of ElmerFEM-gui-nompi-Windows-AMD64 solved an issue of running ElmerGrid on the input mesh from Gmsh.

Added a note for ElmerFEM for Windows (#933)

---

qiskit_metal/_gui/main_window.py

Fix for https://github.com/Qiskit/qiskit-metal/issues/63
https://github.com/Qiskit/qiskit-metal/issues/63
No. UI changes.
No. UI changes.
yes
Fix for https://github.com/Qiskit/qiskit-metal/issues/63
You can filter geometries by Component name and/or layer

Fix for #63 Add QFilterProxy to the elements table

---

qiskit_metal/config.py
qiskit_metal/renderers/renderer_ansys_pyaedt/hfss_renderer_aedt.py
qiskit_metal/tests/test_designs.py

https://github.com/qiskit-community/qiskit-metal/issues/954
Yes- updated method `test_design_get_list_of_tables_in_metadata` in `test_designs.py` 
No - not applicable. Changes are not exposed to front-end user / any function input-output.
Yes
When calling `QHFSSPyaedt.render_design()` it now will update the Ljs in ANSYS.
To reduce confusion for the front-end user, I removed the `QHFSSEigenmodePyaedt` and `QHFSSDrivenmodalPyaedt` from `qiskit_metal.config.py`. Meaning when calling `QComponent.default_options` the user will know only to prompt `options = dict(aedt_hfss_inductance = 10E-9)`

QHFSSPyaedt now updates Ljs

---

qiskit_metal/analyses/quantization/lumped_capacitive.py

Fixes #851 
The dispersion equation in `qiskit_metal\analyses\quantization\lumped_capacitive.py` miscalculated charge dispersion $\epsilon$ by not including a 2 under the square root. Now the calculation matches analytical calculations according to [Charge-insensitive qubit design derived from the Cooper pair box, PhysRevA.76.042319](https://link.aps.org/doi/10.1103/PhysRevA.76.042319).
Before:
After:
I did not add any tests as `test_analyses_2_functionality.py` covers this change. My changes pass `run_all_tests.py`, `test_analyses_2_functionality.py` and `test_analyses_1_inst_options.py`.
I did not update the documentation as the documentation does not pertain to this change. The functionality of the `transmon_props()` method remains the same.
Yes I did.
This brief commit fixes the …

Fixed charge dispersion equation typo in LOM analysis

---

qiskit_metal/renderers/renderer_ansys_pyaedt/hfss_renderer_eigenmode_aedt.py

No - internal change.
No - internal change.
Yes
In https://github.com/qiskit-community/qiskit-metal/pull/955, there were left over calls to `aedt_hfss_eigenmode_inductance` and `aedt_hfss_eigenmode_capacitance`. This PR is to fix that mistake.
Doing a global search through the code reveals that changes included are the only leftover `aedt_hfss_eigenmode_inductance` and `aedt_hfss_eigenmode_capacitance`.
Sorry! Will be more vigilant next time.

Fixed `run_epr` coming from moving renderers

---

docs/conf.py
requirements-dev.txt

Upgrading fixes a weird issue where the nbsphinx tutorials gallery were covering each other.

Upgrade nbpshinx to fix circuit-examples docs

---

docs/installation.rst
environment.yml
requirements.txt

- Documentation of installation was not up date: newest python version 3.11 requires the use of `-f` flag for specifying the environment.yml file.
- Using the latest anaconda installation (as of 07-08-2023), you will get the following error when importing qiskit_metal after installation:
```File "C:\ProgramData\anaconda3\envs\test\Lib\site-packages\qutip\cy\pyxbuilder.py", line 17, in <module>
old_get_distutils_extension = pyximport.pyximport.get_distutils_extension
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pyximport.pyximport' has no attribute 'get_distutils_extension'
```
Which is due to the new cython version 3.0.0 which just came out.
No, this is not needed since there are no code changes but only an added requirement.
yes
yes
Updated documentation of …

Add requirement for cython and update docs

---

.github/workflows/docs.yml
.github/workflows/main.yml
qiskit_metal/qlibrary/user_components/BridgeFreeJJ.py
qiskit_metal/tests/test_qlibrary_3_options.py

This PR fixes the broken CI.
**Summary of the changes:**
- Update the tox version -> tox==4.11.0
- Update the virtualenv version to match the new tox version -> virtualenv==20.19.0
- Fix unit test `test_qlibrary_3_options.py` (line 291, line 490, and lines 499-502)
- Fix the style of `BridgeFreeJJ.py` and `test_qlibrary_3_options.py` for the lint test
The main problem with the CI was that tox wasn't able to set up the test environment. If we look at the errors, tox finds an error when calling the `prepare_metadata_for_build_editable` function. We had that problem because we were pinning tox to use an old version, and the pyproject-api version that we are using (`pyproject-api==1.6.1`) is not able to work with old versions of tox. The solution for this first problem was to change the CI to …

[WIP] Fix broken CI

---

docs/_templates/autosummary/class_no_inherited_members.rst

Moved all the methods and attributes into class pages to speed up the building process of the documentation with the new ecosystem sphinx theme in https://github.com/qiskit-community/qiskit-metal/pull/975. The new theme increases the time building the documentation when we have a lot of pages, and with this PR we can achieve a major speedup.
See https://github.com/Qiskit/qiskit/pull/10455 for more information.

Move methods into class pages for docs

---

qiskit_metal/analyses/quantization/lumped_capacitive.py

Error when running lumped_capacitive.levels_vs_ng_real_units with do_plot = 1.
None. Default setting of the function is do_plots=0, which is the only reason this issue hasn't broken out before. Adjusting this single argument in a plt.plot() call should have no bearing on any other function.
No, since this is covered in the documentation of matplotlib.
Yes, although this seems like such a tiny change, and most of the guidelines overkill in this case.
Changing plt.plot() argument from "LineWidth" to "linewidth" to avoid run error. Specifically the function levels_vs_ng_real_units inside the file lumped_capacitive.py.
Tiny fix for an aggravating bug.

Bug fix lumped_capacitive.py

---

docs/tut/1-Overview/1.2-Quick-start.ipynb
docs/tut/1-Overview/1.3-Saving-Your-Chip-Design.ipynb
docs/tut/2-From-components-to-chip/2.01-How-to-use-a-QComponent.ipynb
docs/tut/2-From-components-to-chip/2.02-How-to-copy-a-QComponent.ipynb
docs/tut/2-From-components-to-chip/2.11-Routing-101.ipynb
docs/tut/2-From-components-to-chip/2.21-Design-a-4-qubit-full-chip.ipynb
docs/tut/4-Analysis/4.02-Eigenmode-and-EPR.ipynb
qiskit_metal/_gui/component_widget_ui.py
qiskit_metal/_gui/component_widget_ui.ui
qiskit_metal/_gui/styles/metal_dark/TODO.txt
setup.py
tutorials/1 Overview/1.2 Quick start.ipynb
tutorials/1 Overview/1.3 Saving Your Chip Design.ipynb
tutorials/2 From components to chip/A. Using QComponents/2.01 How to use a QComponent.ipynb
tutorials/2 From components to chip/A. Using QComponents/2.02 How to copy a QComponent.ipynb
tutorials/2 From components to chip/B. Routing between QComponents/2.11 Routing 101.ipynb
tutorials/2 From components to chip/C. My first full quantum chip design/2.21 Design a 4 qubit full chip.ipynb
tutorials/4 Analysis/A. Core - EM and quantization/4.02 Eigenmode and EPR.ipynb

Fix #1006
No need
No need
Yes
Add missing gui styles when installing with pip and fix some typos
Add missing gui styles when installing with pip and fix some typos

Add missing gui styles when installing
